services:
  web:
    image: php:8.2-apache
    container_name: php_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
